<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net10.0-android;net10.0-ios</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SharedUI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazor.ApexCharts" Version="3.0.0-beta.9" />
  </ItemGroup>

</Project>
